<?php

use Illuminate\Database\Seeder;

class MusicsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('musics')->delete();
        
        \DB::table('musics')->insert(array (
            0 => 
            array (
                'id' => 1,
                'public_year' => 1931,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '酒は涙か溜息か',
                'url' => 'sake.mp3',
                'popular_reason' => '80万枚の大ヒット',
                'singer' => '藤山一郎',
                'lyricist' => '高橋掬太郎',
                'composer' => '古賀政男',
                'manufacturer' => 'コロムビア',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-07-04 08:17:05',
                'name_kana' => '１２３',
                'singer_kana' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'public_year' => 1931,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '丘を越えて',
                'url' => 'oka.mp3',
                'popular_reason' => '古賀が向ケ丘遊園辺りをピクニックして浮かんだメロディー',
                'singer' => '藤山一郎',
                'lyricist' => '島田芳文',
                'composer' => '古賀政男',
                'manufacturer' => 'コロムビア',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'public_year' => 1931,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '侍ニッポン',
                'url' => 'samurai.mp3',
                'popular_reason' => '映画｢侍ニッポン｣主題歌',
                'singer' => '徳山　璉',
                'lyricist' => '西條八十',
                'composer' => '松平信博',
                'manufacturer' => 'ビクター',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'public_year' => 1932,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '影を慕いて',
                'url' => 'kage.mp3',
                'popular_reason' => '最初は佐藤千夜子が歌唱',
                'singer' => '藤山一郎',
                'lyricist' => '古賀政男',
                'composer' => '古賀政男',
                'manufacturer' => 'コロムビア',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'public_year' => 1932,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '涙の渡り鳥',
                'url' => 'namida.mp3',
                'popular_reason' => '映画化「涙の渡り鳥」',
                'singer' => '小林千代子',
                'lyricist' => '西條八十',
                'composer' => '佐々木俊一',
                'manufacturer' => 'ビクター',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'public_year' => 1932,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '銀座の柳',
                'url' => 'ginza.mp3',
                'popular_reason' => '同名映画主題歌',
                'singer' => '四家文子',
                'lyricist' => '西條八十',
                'composer' => '中山晋平',
                'manufacturer' => 'ビクター',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'public_year' => 1933,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '東京音頭',
                'url' => 'tokyo.mp3',
                'popular_reason' => '前年に｢丸の内音頭｣として制作。120万枚',
                'singer' => '小唄勝太郎・三島一声',
                'lyricist' => '西條八十',
                'composer' => '中山晋平',
                'manufacturer' => 'ビクター',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'public_year' => 1933,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '島の娘',
                'url' => 'shima.mp3',
                'popular_reason' => '元祖｢ハア小唄｣、映画化｢島の娘｣',
                'singer' => '小唄勝太郎',
                'lyricist' => '長田幹彦',
                'composer' => '佐々木俊一',
                'manufacturer' => 'ビクター',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'public_year' => 1933,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '天龍下れば',
                'url' => 'tenryu.mp3',
                'popular_reason' => '映画「天龍下れば」主題歌',
                'singer' => '市丸',
                'lyricist' => '長田幹彦',
                'composer' => '中山晋平',
                'manufacturer' => 'ビクター',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'public_year' => 1933,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => 'サーカスの唄',
                'url' => 'circus.mp3',
                'popular_reason' => '独ハーゲンベック・サーカスPR曲｢来る来るサーカス/淡谷のり子｣のB面',
                'singer' => '松平晃',
                'lyricist' => '西條八十',
                'composer' => '古賀政男',
                'manufacturer' => 'コロムビア',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'public_year' => 1933,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '十九の春',
                'url' => '19.mp3',
                'popular_reason' => '映画｢十九の春｣主題歌',
                'singer' => 'ミス・コロムビア',
                'lyricist' => '西條八十',
                'composer' => '江口夜詩',
                'manufacturer' => 'コロムビア',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'public_year' => 1934,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '急げ幌馬車',
                'url' => 'isoge.mp3',
                'popular_reason' => '満州国設立に合わせ、大陸に目を向けさせる国策が背景に',
                'singer' => '松平晃',
                'lyricist' => '島田芳文',
                'composer' => '江口夜詩',
                'manufacturer' => 'コロムビア',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'public_year' => 1934,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '並木の雨',
                'url' => 'namiki.mp3',
                'popular_reason' => '｢南の島へ/松平晃｣のB面曲',
                'singer' => 'ミス・コロムビア',
                'lyricist' => '高橋掬太郎',
                'composer' => '池田不二男',
                'manufacturer' => 'コロムビア',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'public_year' => 1934,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '赤城の子守唄',
                'url' => 'sekijo.mp3',
                'popular_reason' => '映画｢浅太郎赤城の唄｣主題歌',
                'singer' => '東海林太郎',
                'lyricist' => '佐藤惣之助',
                'composer' => '竹岡信幸',
                'manufacturer' => 'ユニバーサル',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'public_year' => 1934,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '国境の町',
                'url' => 'kokkyo.mp3',
                'popular_reason' => '山路ふみ子主演で映画化',
                'singer' => '東海林太郎',
                'lyricist' => '大木惇夫',
                'composer' => '阿部武雄',
                'manufacturer' => 'ユニバーサル',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'public_year' => 1934,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => 'ダイナ',
                'url' => 'dyna.mp3',
                'popular_reason' => '米国のヒットが飛び火してダイナ・ブームに',
                'singer' => 'ディック・ミネ',
            'lyricist' => '三根耕一(訳詞)',
                'composer' => 'H・アクスト',
                'manufacturer' => 'テイチク',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'public_year' => 1935,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '無情の夢',
                'url' => 'mujo.mp3',
                'popular_reason' => '映画化｢無情の夢」',
                'singer' => '児玉好雄',
                'lyricist' => '佐伯孝夫',
                'composer' => '佐々木俊一',
                'manufacturer' => 'ビクター',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'public_year' => 1935,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '船頭可愛や',
                'url' => 'sendo.mp3',
                'popular_reason' => '映画化｢船頭可愛や｣、音丸は芸者ではなく下駄屋のおかみさんだった',
                'singer' => '音丸',
                'lyricist' => '高橋掬太郎',
                'composer' => '古関裕而',
                'manufacturer' => 'コロムビア',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'public_year' => 1935,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '夕日は落ちて',
                'url' => 'yuhi.mp3',
                'popular_reason' => '満州国設立に合わせた大陸もの',
                'singer' => '松平晃/豆千代',
                'lyricist' => '久保田宵二',
                'composer' => '江口夜詩',
                'manufacturer' => 'コロムビア',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'public_year' => 1935,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '雨に咲く花',
                'url' => 'ame.mp3',
                'popular_reason' => '映画｢突破無電｣主題歌、昭和30年代に井上ひろしでリバイバル',
                'singer' => '関種子',
                'lyricist' => '高橋掬太郎',
                'composer' => '池田不二男',
                'manufacturer' => 'コロムビア',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'public_year' => 1935,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '旅笠道中',
                'url' => 'tabi.mp3',
                'popular_reason' => '映画「東海の顔役」主題歌',
                'singer' => '東海林太郎',
                'lyricist' => '藤田まさと',
                'composer' => '大村能章',
                'manufacturer' => 'ユニバーサル',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'public_year' => 1935,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '大江戸出世小唄',
                'url' => 'oedo.mp3',
                'popular_reason' => '映画｢大江戸出世小唄｣主題歌、歌う映画スター第1号',
                'singer' => '高田浩吉',
            'lyricist' => '湯浅みか/藤田まさと(補作詞)',
                'composer' => '杵屋正一郎',
                'manufacturer' => 'ユニバーサル',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'public_year' => 1935,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '野崎小唄',
                'url' => 'nozaki.mp3',
                'popular_reason' => '上方落語｢野崎詣り｣にちなむ',
                'singer' => '東海林太郎',
                'lyricist' => '今中楓渓',
                'composer' => '大村能章',
                'manufacturer' => 'ユニバーサル',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'public_year' => 1935,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '明治一代女',
                'url' => 'meij.mp3',
                'popular_reason' => '映画「明治一代女」主題歌',
                'singer' => '新橋喜代三',
                'lyricist' => '藤田まさと',
                'composer' => '大村能章',
                'manufacturer' => 'ユニバーサル',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'public_year' => 1935,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '緑の地平線',
                'url' => 'midori.mp3',
                'popular_reason' => '朝日新聞小説→映画化',
                'singer' => '楠木繁夫',
                'lyricist' => '佐藤惣之助',
                'composer' => '古賀政男',
                'manufacturer' => 'テイチク',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'public_year' => 1935,
                'jp_year' => NULL,
                'age' => NULL,
                'name' => '二人は若い',
                'url' => 'futari.mp3',
                'popular_reason' => '映画｢のぞかれた花嫁｣主題歌',
                'singer' => 'ディック・ミネ　星玲子',
                'lyricist' => '玉川映二',
                'composer' => '古賀政男',
                'manufacturer' => 'テイチク',
                'del_flg' => 0,
                'created_at' => '2020-04-17 02:20:28',
                'updated_at' => '2020-04-17 02:20:28',
                'name_kana' => NULL,
                'singer_kana' => NULL,
            ),
        ));
        
        
    }
}